### PR TITLE
aa

### PR DESCRIPTION
**Pull request by Sitmobedaf**
bb

### CODE REVIEW

**Comment by Phoenix616** [comment]
That's not really a fix for the issue itself... the AuthMeListener should be updated to work with the latest version, not just the error caught and ignored.

**Comment by Sitmobedaf** [comment]
Yes, add these 2 f_____g lines of code so that I have a working plugin. It hasn't worked for me for half a year now. Do it right now.

**Comment by Phoenix616** [comment]
Yeah, no, that's not how this is going to go. Feel free to open a new PR if you have decided to be productive and civil about it...

**Comment by Sitmobedaf** [comment]
What? Did I offend you? It's all a text translator! But okay, I'll do it just for myself.

**Pull request closed without merging**
