### PR TITLE
Add shulker boxes to list of possible shop containers

### PR DESCRIPTION
**Pull request by FootInMySalad**

### CODE REVIEW

**Comment by FootInMySalad** [comment]
Wait nevermind

**Comment by FootInMySalad** [comment]
I accidentally closed the pull request.

**Comment by FootInMySalad** [comment]
I noticed an issue, I will reopen this once the issue is fixed.

**Comment by Phoenix616** [comment]
Yeah, you only added the default, non-dyed box.

Also I don't really see the value of adding them to the default config. They aren't chests (as indicated by the plugin name) and if someone really wants them to work as shop containers they could just add them manually to the list in their config.

**Pull request closed without merging**
