### PR TITLE
This should fix EssentialsX issue with reporting wrong balance. 

### PR DESCRIPTION
**Pull request by simon44556**
This uses the provider so it uses the essentials function to compare the balance which uses BigDecimal

### CODE REVIEW

**Comment by Phoenix616** [comment]
This is removing the partial item check for an amount event call for the single item price instead of the full end price?

You need to keep the amount check in (purchasing 0 items doesn't make sense) and check for the final price (partial amount * item price)

**Comment by simon44556** [comment]
The problem is if a player has 49.9999999999999999999$ when you convert to dobuble it gets rounded to 50.0 so players were using this to get infinite money. The main problem is in essentialsx as it uses BigDecimal to store the value of money. This fixes the problem as it uses the essentials function through vault and compares it with the real amount of money.

**Comment by Phoenix616** [comment]
Can you please explain what this pull request is supposed to change from the code that is already in place? The `getAmountOfAffordableItems` method already only returns the amount of items that the player can afford to buy, there should be no need to check whether or not the player has enough money again. If the issue is that the item amount method returns erroneous values then it should be fixed directly instead of calling the same check event twice.

Also if the issue is just due to some economy plugin returning wrong balance values then that should be fixed in the economy plugin directly.

**Comment by Melacraft** [comment]
Hi, how do I solve this? I am new here. But reading your messages do NOT place how to solve it.
Sorry for ENGLISH but I am a person who speaks Spanish.

**Comment by TheDGOfficial** [comment]
It's already fixed, make sure you have latest EssentialsX and ChestShop.
https://github.com/Minebench/Essentials/commit/4411af096a1176969e6b1c48e6c6b27fe5e7e3db https://github.com/ChestShop-authors/ChestShop-3/commit/fc62ab0823ccae1c1b874ff2b4ea1b7848b51d55 https://github.com/EssentialsX/Essentials/issues/2101

**Comment by Melacraft** [comment]
Muchas gracias.

**Pull request closed without merging**
