### PR TITLE
add compatibility with material-compatible lwc

### PR DESCRIPTION
**Pull request by jascotty2**

### CODE REVIEW

**Comment by Phoenix616** [comment]
Where is that version of LWC from? Also is there really no maven repository that includes it? Adding it to the git repository manually should really only be used as a last resort... (e.g. [my LWC fork](https://github.com/Minebench/LWC) that uses Material types for registering protections is included in the Minebech repo too)

**Comment by jascotty2** [comment]
Based on the same fork that the one you link is based on, https://github.com/dmulloy2/LWC

I've added a number of additions to make it 1.14 compatible, fix the new chest types + manual entity locking, but the material method is the same.

**Comment by jascotty2** [comment]
Supposedly there's a maven, but it's not where I thought it should be..

**Comment by Phoenix616** [comment]
You can just use my repo (https://repo.minebench.de) which includes my LWC fork with the same kind of Material method.

Also I thought a bit about this and would even be in favour of completely removing support for non-Material based LWC methods seeing as ChestShop itself is not backwards compatible to anything before 1.13 and any 1.13 plugin should be using Materials and not arbitrary IDs in their API methods to begin with. (And running outdated LWC versions really breaks stuff)

**Comment by Phoenix616** [comment]
I've implemented another solution for the LWC issues in f90d23cfc3d4c699c07b80f40dff59c331c48d18 so I'm closing this PR for now. If you have any issues with the implemented solution let me know/send a PR to propose changes. :)

**Pull request closed without merging**
